baseURL = 'https://ibrahimalanshor.me'
languageCode = 'en-us'
title = 'My New Hugo Site'
enableRobotsTXT = true

disableKinds = ['taxonomy', 'term']

[permalinks]
  blogs = '/:title'
  projects = '/projects/:title'